import Nav from "@/components/nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} white`}>
        <header className = "flex items-center justify-start gap-10 shadow-md">
          <img
            className="w-20 h-20 m-2"
            src="https://pbs.twimg.com/profile_images/1674021935754407937/K6MklT1G_400x400.jpg"
          ></img>
        <Nav/>
        </header>
        <footer></footer>
        {children}
      </body>
    </html>
  );
}
